image: registry.gitlab.com/siderus/toolchain

services:
  - docker:dind

stages:
  - test
  - release
  - postrelease

before_script:
  - mv package.json package.json.old
  - cat package.json.old | jq 'to_entries | map(if .key == "env" then .value = "release" else . end) | from_entries' > package.json
  - rm -f package.json.old
  - mv package.json package.json.old
  - cat package.json.old | jq 'to_entries | map(if .key == "statsToken" then .value = "bcd802fa2e699f85cc19e1ff6079e3c7" else . end) | from_entries' > package.json
  - rm -f package.json.old

yarn-test:
  stage: test
  script:
    - docker run --rm -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "make lint test"
  only:
    - master

yarn-release:
  stage: release
  retry: 2
  script:
    - docker run --rm -e GH_TOKEN="${GH_TOKEN}" -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "make release_all"
  only:
    - master

trigger-repository:
  stage: postrelease
  script:
    - curl -X POST -F token=${TRIGGER_REPO_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/7744513/trigger/pipeline
  only:
    - master
