image: registry.gitlab.com/siderus/toolchain

services:
  - docker:dind

stages:
  - test
  - release

yarn-test:
  stage: test
  tags:
    - docker
  script:
    - docker run --rm -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "yarn && yarn test"
  only:
    - master

yarn-release:
  stage: release
  tags:
    - docker
  script:
    - docker run --rm -e GH_TOKEN="${GH_TOKEN}" -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release-all"
  only:
    - master
