image: registry.gitlab.com/siderus/toolchain

services:
  - docker:dind

stages:
  - test
  - release

before_script:
  - mv package.json package.json.old
  - cat package.json.old | jq 'to_entries | map(if .key == "env" then .value = "release" else . end) | from_entries' > package.json
  - rm -f package.json.old

yarn-test:
  stage: test
  tags:
    - docker
  script:
    - docker run --rm -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "make lint test"
  only:
    - master

yarn-release:
  stage: release
  when: manual
  tags:
    - docker
  script:
    - docker run --rm -e GH_TOKEN="${GH_TOKEN}" -v ${PWD}:/project electronuserland/builder:wine /bin/bash -c "make release_all"
  only:
    - master
