image: electronuserland/builder:wine

services:
  - docker:dind

cache:
  # Enables cache on Node Modules on the same branch
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - test
  - pre-release
  - release
  - post-release

yarn:test:
  stage: test
  script:
    - make lint test


yarn:build:mac:
  stage: pre-release
  retry: 2
  script:
    - make build -e OS=Darwin -e UNAME_S=Darwin
  artifacts:
    paths:
    - build
    expire_in: 1 week
  only:
    - /release.*/

yarn:build:win:
  stage: pre-release
  retry: 2
  script:
    - make build -e OS=Windows_NT
  artifacts:
    paths:
    - build
    expire_in: 1 week
  only:
    - /release.*/

yarn:build:gnu:
  stage: pre-release
  retry: 2
  script:
    - make build -e OS=Linux -e UNAME_S=Linux
  artifacts:
    paths:
    - build
    expire_in: 1 week
  only:
    - /release.*/


yarn:release:master:
  stage: release
  retry: 2
  script:
    - make prepare_release release_all snap_publish
  cache: {} # Disable cache
  artifacts:
    paths:
    - build
    expire_in: 3 months
  only:
    - tags


trigger_upload:
  stage: post-release
  script:
    - curl -X POST -F token=${TRIGGER_REPO_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/7744513/trigger/pipeline
  only:
    - tags