language: node_js
node_js:
  - "node"
cache:
  yarn: true
matrix:
  include:
  - os: linux
  - os: osx

notifications:
  email: false

script:
  - yarn test --coverage
  - yarn lint

before_deploy:
  - yarn make

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: out/make/*
  skip_cleanup: true
  on:
    tags: true
